### ISSUE TITLE
fix(setup):  casa url should be provide after installation

### ISSUE THREAD

**Issue by manojs1978** [GluuFederation/flex#1393]
**Describe the bug**
casa url should be provide while installation

**To Reproduce**
1. install flex 5.0.19
2. first jans will be installed while installation it select casa as yes
3. when flex installation started we will not get any prompt for install casa

**Expected behavior**
casa url should be display at the installation end

**Screenshots**
![image](https://github.com/GluuFederation/flex/assets/5729240/a255ee48-cb87-4415-a827-239ccd04f067)

**Desktop (please complete the following information):**
  - OS: suse/ubuntu/rhel
  - Browser 
  - Version 
  - flex  5.0.0-19
  - DB mysql/pgsql/opendj

**Smartphone (please complete the following information):**

**Additional context**

**Comment by devrimyatar** [comment]
When you install casa within flex-setup, it displays

![image](https://github.com/GluuFederation/flex/assets/6398752/83953214-9b61-4185-9cd5-697d7b4b6c44)

When you install casa within jans-setup, it is fixed with https://github.com/JanssenProject/jans/pull/6315

Thus there is nothing to do for this issue.
