### ISSUE TITLE
Admin UI: Code Review

### ISSUE THREAD

**Issue by duttarnab** [GluuFederation/flex#3]
**Tasks:** 
 Do code review of Admin UI Frontend code (react/redux) and make a list of the following in an excel sheet.
1. Bottlenecks in application
2. Improper code practices
3. Improvements required on GUI 
4. Review existing techniques used to implement plugin architecture in the frontend and suggest improvements (if any).
5. Execute the below command to find vulnerabilities in dependencies used by the project and fix those vulnerabilities 
```
npm run audit
```

**Comment by harryandriyan** [comment]
## **Admin UI: Code Review**

### Code Improvement

- Use consistent functional components, some components still use class-based
- Organize the Redux folder based on component
- Some code not aligned with defined lint rule: fixed with `npm run lint`
- We need to define the relative path to make the import section code clean and easy to manage
for example importing `../../utils/TokenController` we can make it `import { someFunc } from  @utils/TokenController`
- Avoid importing whole lodash library `import _ from 'lodash'`
Alternative, we can import specific method of the lodash library 
`import map from 'lodash/map'`

<will be updated regularly>
