### ISSUE TITLE
Enhancement(admin-ui): Explore the possibility of using redux-toolkit to improve the redux code

### ISSUE THREAD

**Issue by syntrydy** [GluuFederation/flex#81]
Please check the doc here https://redux-toolkit.js.org/introduction/getting-started

**Comment by mjatin-dev** [comment]
Hi @syntrydy , to convert our application to the redux toolkit standards, we need to start from the store, as per toolkit standards store will be defined as `configureStore` instead of `createStore` moreover we need to change all the action methods to the `slice` which is toolkit standard and need to link all the saga actions to the slice itself. 

Overall I can say we need to define almost all the things used in redux again to the toolkit standards.

**Comment by jv18creator** [comment]
We can define action methods in `slice` & keep the `saga` logic as it is. That way we won't have to create everything from scratch. The only thing will change in this case will be way of writing reducer. Instead of defining into seperate file, we could define it in `slice`. @duttarnab please review https://github.com/GluuFederation/flex/commit/483774d44d66bf7194cddc83b8a34be2c68751aa

**Comment by duttarnab** [comment]
Done for scope, session. We will raise issue for rest of code.
